export const contentMap: any = {
  carpet: [
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
    'project.circle_carpet_title',
    'project.circle_carpet_description1',
    'project.circle_carpet_description2',
  ],
  stone_ceramic_flooring: [
    'project.select_tile_pattern',
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
  ],
  stone_ceramic_wall_covering: [
    'project.select_tile_pattern',
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
  ],
  frame: [
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
  ],
  curtain: [
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
  ],
  wallpaper: [
    'project.select_tile_pattern',
    'project.choose_name_description1',
    'project.choose_name_description2',
    'project.choose_name_description3',
    'project.project_image_info2',
    'project.size_each_photo_must_1mb',
    'project.photos_front_view_without_extra_borders',
  ],
  furniture: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  home_appliances: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  wall_mounted: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  watch: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  glasses: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  bracelet: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  ring: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  earrings: [
    'project.earring_photos_should_be_transparent',
    'project.image_format_png',
    'project.image_size_maximum_1mb',
    'project.image_have_no_margins',
    'project.images_should_front_view_not_pair',
    'project.guide_enter_length_width_earring',
  ],
  necklace: [
    'project.necklace_photos_should_be_transparent',
    'project.image_format_png',
    'project.image_size_maximum_1mb',
    'project.necklace_image_have_no_margins',
    'project.images_should_front_view',
    'project.guide_enter_length_width_necklace',
  ],
  video: [
    'project.marker_image_description',
    'project.image_file_format_jpg_png',
    'project.file_size_must_less1mb',
    'project.video_file_follow_guidelines',
    'project.video_file_format_must_mp4',
    'project.file_size_must_less_10mb',
    'project.cta_buttons_description',
    'project.phone_number',
    'project.mobile_number',
    'project.website_custom_link',
    'project.telegram',
    'project.instagram',
    'project.linkedIn',
    'project.address_location',
  ],
  industrial_products: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  food_industry: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  gamification: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world_gamificashion',
    'project.model_placement_match_sample',
  ],
  shoes: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  hat: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_placement_match_sample',
  ],
  fashion: [
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
    'project.model_size_match_real_world',
    'project.model_placement_match_sample',
  ],
  bow_tie: [
    'project.tie_photos_should_be_transparent',
    'project.image_format_png',
    'project.image_size_maximum_1mb',
    'project.tie_image_have_no_margins',
    'project.images_should_front_view',
    'project.guide_enter_length_width_tie',
  ],
  ar_3d: [
    'project.showroom_guideline1',
    'project.showroom_guideline2',
    'project.showroom_guideline3',
    'project.showroom_guideline4',
    'project.showroom_guideline5',
    'project.size_each_photo_must_1mb',
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
  ],
  '3d': [
    'project.showroom_guideline1',
    'project.showroom_guideline2',
    'project.showroom_guideline3',
    'project.showroom_guideline4',
    'project.showroom_guideline5',
    'project.size_each_photo_must_1mb',
    'project.file_must_glb_format',
    'project.file_size_should_15mb',
    'project.glb_format_must_pbr',
  ],
};

// Define the mapping outside your component
export const downloadUrls: any = {
  furniture: 'https://armogroup.storage.iran.liara.space/3D-model/furniture.glb',
  home_appliances: 'https://armogroup.storage.iran.liara.space/3D-model/home_appliances.glb',
  wall_mounted: 'https://armogroup.storage.iran.liara.space/3D-model/wall_mounted.glb',
  watch: 'https://armogroup.storage.iran.liara.space/3D-model/watch.glb',
  glasses: 'https://armogroup.storage.iran.liara.space/3D-model/glasses.glb',
  bracelet: 'https://armogroup.storage.iran.liara.space/3D-model/bracelet.glb',
  ring: 'https://armogroup.storage.iran.liara.space/3D-model/ring.glb',
  industrial_products:
    'https://armogroup.storage.iran.liara.space/3D-model/industrial_products.glb',
  food_industry: 'https://armogroup.storage.iran.liara.space/3D-model/food_industry.glb',
  gamification: 'https://armogroup.storage.iran.liara.space/3D-model/gamification.glb',
  shoes: 'https://armogroup.storage.iran.liara.space/3D-model/shoes.glb',
  hat: 'https://armogroup.storage.iran.liara.space/3D-model/hat.glb',
  fashion: 'https://armogroup.storage.iran.liara.space/3D-model/fashion.glb',
  ar_3d: 'https://armogroup.storage.iran.liara.space/3D-model/gamification.glb',
  '3d': 'https://armogroup.storage.iran.liara.space/3D-model/gamification.glb',
  // Add other categories as necessary
};
