export const solutions_description = (t: Function) => [
  {
    title: t('our_solutions.cosmetics_title'),
    subtitle: t('our_solutions.cosmetics_description1'),
    introduction: t('our_solutions.cosmetics_description2'),
    features: [
      t('our_solutions.cosmetics_description3'),
      t('our_solutions.cosmetics_description4'),
      t('our_solutions.cosmetics_description5'),
    ],
    mainText: t('our_solutions.cosmetics_description6'),
    conclusion: t('our_solutions.cosmetics_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/makeup.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/beauty.svg',
    link: '/makeup',
  },
  {
    title: t('our_solutions.furniture_title'),
    subtitle: t('our_solutions.furniture_description1'),
    introduction: t('our_solutions.furniture_description2'),
    features: [
      t('our_solutions.furniture_description3'),
      t('our_solutions.furniture_description4'),
      t('our_solutions.furniture_description5'),
    ],
    mainText: t('our_solutions.furniture_description6'),
    conclusion: t('our_solutions.furniture_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_furniture.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/furniture.svg',
    link: '',
  },
  {
    title: t('our_solutions.carpet_title'),
    subtitle: t('our_solutions.carpet_description1'),
    introduction: t('our_solutions.carpet_description2'),
    features: [
      t('our_solutions.carpet_description3'),
      t('our_solutions.carpet_description4'),
      t('our_solutions.carpet_description5'),
    ],
    mainText: t('our_solutions.carpet_description6'),
    conclusion: t('our_solutions.carpet_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_carpet.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/carpet.svg',
    link: '/ar-carpet',
  },
  {
    title: t('our_solutions.fashion_title'),
    subtitle: t('our_solutions.fashion_description1'),
    introduction: t('our_solutions.fashion_description2'),
    features: [
      t('our_solutions.fashion_description3'),
      t('our_solutions.fashion_description4'),
      t('our_solutions.fashion_description5'),
    ],
    mainText: t('our_solutions.fashion_description6'),
    conclusion: t('our_solutions.fashion_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_apparel_fittings.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/outfit.svg',
    link: '',
  },
  {
    title: t('our_solutions.footwear_title'),
    subtitle: t('our_solutions.footwear_description1'),
    introduction: t('our_solutions.footwear_description2'),
    features: [
      t('our_solutions.footwear_description3'),
      t('our_solutions.footwear_description4'),
      t('our_solutions.footwear_description5'),
    ],
    mainText: t('our_solutions.footwear_description6'),
    conclusion: t('our_solutions.footwear_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_shoes.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/shoes.svg',
    link: '',
  },
  {
    title: t('our_solutions.eyewear_title'),
    subtitle: t('our_solutions.eyewear_description1'),
    introduction: t('our_solutions.eyewear_description2'),
    features: [
      t('our_solutions.eyewear_description3'),
      t('our_solutions.eyewear_description4'),
      t('our_solutions.eyewear_description5'),
    ],
    mainText: t('our_solutions.eyewear_description6'),
    conclusion: t('our_solutions.eyewear_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_eyewear.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/glasses.svg',
    link: '',
  },
  {
    title: t('our_solutions.jewelry_title'),
    subtitle: t('our_solutions.jewelry_description1'),
    introduction: t('our_solutions.jewelry_description2'),
    features: [
      t('our_solutions.jewelry_description3'),
      t('our_solutions.jewelry_description4'),
      t('our_solutions.jewelry_description5'),
    ],
    mainText: t('our_solutions.jewelry_description6'),
    conclusion: t('our_solutions.jewelry_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_accessories.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/earrings.svg',
    link: '',
  },
  {
    title: t('our_solutions.home_and_kitchen_title'),
    subtitle: t('our_solutions.home_and_kitchen_description1'),
    introduction: t('our_solutions.home_and_kitchen_description2'),
    features: [
      t('our_solutions.home_and_kitchen_description3'),
      t('our_solutions.home_and_kitchen_description4'),
      t('our_solutions.home_and_kitchen_description5'),
    ],
    mainText: t('our_solutions.home_and_kitchen_description6'),
    conclusion: t('our_solutions.home_and_kitchen_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_home_kitchen.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/home_appliances.svg',
    link: '',
  },
  {
    title: t('our_solutions.ar_video_title'),
    subtitle: t('our_solutions.ar_video_description1'),
    introduction: t('our_solutions.ar_video_description2'),
    features: [
      t('our_solutions.ar_video_description3'),
      t('our_solutions.ar_video_description4'),
      t('our_solutions.ar_video_description5'),
    ],
    mainText: t('our_solutions.ar_video_description6'),
    conclusion: t('our_solutions.ar_video_description7'),
    banner: 'https://armogroup.storage.iran.liara.space/landing/solutions_video.webp',
    icon: 'https://armogroup.storage.iran.liara.space/icons/video.svg',
    link: '',
  },
];
