export type ToggleOfficialResponseType = {
  statusCode: number;
  data: {
    ID: number;
    biography: 'توسعه دهنده نرم‌افزار. یک فرهیخته انتخاب شده عمل میکند و محدودیت را نعمتی از طرف خالق می‌داند. با پیانو ای با بینهایت کلید هیچ آهنگی نمیتوان ساخت';
    rate: number;
    name: string;
    title: string;
    email: string;
    phone: string;
    grade: number;
    id_code: string;
    password: string;
    last_name: string;
    username: string;
    nickname: string;
    avatar_url: string;
    country_code: string;
    city: string;
    date_of_birth: null;
    gender: string;
    suspended_at: Date;
    made_official_at: Date;
    phone_verified_at: Date;
    email_verified_at: Date;
    profile_completed_at: Date;
    made_profile_public_at: null;
    roles: null;
    stars: null;
    invite: null;
    crafts: null;
    socials: null;
    invoices: null;
    documents: null;
    credit_cards: null;
    address_book: null;
    created_at: Date;
    updated_at: Date;
    deleted_at: number;
  };
};
