export const ar_model = (t: Function) => [
  {
    id: 1,
    name: t('landing.ar_for_carpet'),
    description: t('landing.ar_for_carpet_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/carpet.glb',
    ar_link: 'https://webar.armogroup.tech/3b99333b-057d-11ef-8990-ce93120ecbab',
  },
  {
    id: 18,
    name: t('landing.ar_for_automobiles'),
    description: t('landing.ar_for_automobiles_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/haima-s7-darkblue.glb',
    ar_link: 'https://webar.armogroup.tech/992dce6f-c5c8-11ef-9711-ce93120ecbab',
  },
  {
    id: 2,
    name: t('landing.ar_for_furniture'),
    description: t('landing.ar_for_furniture_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/furniture.glb',
    ar_link: 'https://webar.armogroup.tech/3f2416ba-0576-11ef-8990-ce93120ecbab',
  },
  {
    id: 3,
    name: t('landing.ar_for_home'),
    description: t('landing.ar_for_home_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/home_appliances.glb',
    ar_link: 'https://webar.armogroup.tech/0f2c2047-0578-11ef-8990-ce93120ecbab',
  },
  {
    id: 4,
    name: t('landing.ar_for_creative_campaigns'),
    description: t('landing.ar_for_creative_campaigns_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/campaign.glb',
    ar_link: 'https://webar.armogroup.tech/1728b20d-0618-11ef-8990-ce93120ecbab',
  },
  {
    id: 5,
    name: t('landing.ar_for_restaurant_menu'),
    description: t('landing.ar_for_restaurant_menu_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/menu.glb',
    ar_link: 'https://webar.armogroup.tech/8e60f419-057e-11ef-8990-ce93120ecbab',
  },
  {
    id: 6,
    name: t('landing.ar_for_shoes'),
    description: t('landing.ar_for_shoes_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/shoes.glb',
    ar_link: 'https://webar.armogroup.tech/8227e5a1-0573-11ef-8990-ce93120ecbab',
  },
  {
    id: 7,
    name: t('landing.ar_for_glasses'),
    description: t('landing.ar_for_glasses_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/glasses.glb',
    ar_link: 'https://tryon-glasses.armogroup.tech/cb71fe65-0610-11ef-8990-ce93120ecbab',
  },
  {
    id: 8,
    name: t('landing.ar_for_artwork'),
    description: t('landing.ar_for_artwork_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/artwork.glb',
    ar_link: 'https://webar.armogroup.tech/ce298bd2-060c-11ef-8990-ce93120ecbab',
  },
  {
    id: 9,
    name: t('landing.ar_for_stone_ceramics'),
    description: t('landing.ar_for_stone_ceramics_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/stone.glb',
    ar_link: 'https://webar.armogroup.tech/1700c410-0613-11ef-8990-ce93120ecbab',
  },
  {
    id: 10,
    name: t('landing.ar_for_jewelry'),
    description: t('landing.ar_for_jewelry_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/jewelry.glb',
    ar_link: 'https://reality.armogroup.tech/tryon/serve/7d88b82e-08c2-11ef-9e11-ce93120ecbab',
  },
  {
    id: 11,
    name: t('landing.ar_for_wallpapers'),
    description: t('landing.ar_for_wallpapers_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/wallpaper.glb',
    ar_link: 'https://webar.armogroup.tech/2ae7f18c-0612-11ef-8990-ce93120ecbab',
  },
  {
    id: 12,
    name: t('landing.ar_for_watches'),
    description: t('landing.ar_for_watches_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/watch.glb',
    ar_link: 'https://webar.armogroup.tech/561a19db-060f-11ef-8990-ce93120ecbab',
  },
  {
    id: 13,
    name: t('landing.ar_for_industries'),
    description: t('landing.ar_for_industries_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/industry.glb',
    ar_link: 'https://webar.armogroup.tech/211391c7-0617-11ef-8990-ce93120ecbab',
  },
  {
    id: 14,
    name: t('landing.ar_for_sportswear'),
    description: t('landing.ar_for_sportswear_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/sportwear.glb',
    ar_link: 'https://webar.armogroup.tech/87e89cc8-0616-11ef-8990-ce93120ecbab',
  },
  {
    id: 15,
    name: t('landing.ar_for_hats'),
    description: t('landing.ar_for_hats_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/hat.glb',
    ar_link: 'https://webar.armogroup.tech/21b81782-0614-11ef-8990-ce93120ecbab',
  },
  {
    id: 17,
    name: t('landing.ar_for_digital_products'),
    description: t('landing.ar_for_digital_products_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/iphone13red%20.glb',
    ar_link: 'https://webar.armogroup.tech/showroom/e9d49852-c5e0-11ef-9711-ce93120ecbab',
  },
  {
    id: 16,
    name: t('landing.ar_for_toys'),
    description: t('landing.ar_for_toys_description'),
    src: 'https://armogroup.storage.iran.liara.space/landing-3d-model/toy.glb',
    ar_link: 'https://webar.armogroup.tech/67d1facd-0615-11ef-8990-ce93120ecbab',
  },
];
