export const customersList = [
  'https://armogroup.storage.iran.liara.space/customers/banilogo.webp',
  'https://armogroup.storage.iran.liara.space/customers/me-new.webp',
  'https://armogroup.storage.iran.liara.space/customers/lunato-logo.webp',
  'https://armogroup.storage.iran.liara.space/customers/roja.webp',
  'https://armogroup.storage.iran.liara.space/customers/choobsang.webp',
  'https://armogroup.storage.iran.liara.space/customers/ELENCI-COLOR3-min.webp',
  'https://armogroup.storage.iran.liara.space/customers/maxen.webp',
  'https://armogroup.storage.iran.liara.space/customers/dinial.webp',
  'https://armogroup.storage.iran.liara.space/customers/e-farsh.webp',
  'https://armogroup.storage.iran.liara.space/customers/navid-akradi.webp',
  'https://armogroup.storage.iran.liara.space/customers/farsh-afrand.webp',
  'https://armogroup.storage.iran.liara.space/customers/negincarpet.webp',
  'https://armogroup.storage.iran.liara.space/customers/zeeen.webp',
];
